/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.test.java.org.mike_physics_sim;

import org.junit.jupiter.api.Test;

import src.main.java.org.mike_physics_sim.Library;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
