/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src.main.java.org.mike_physics_sim;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
